- platform: mqtt
  name: "<thermostat_name>"
  qos: 0
  retain: false
  send_if_off: false
  initial: 25
  current_temperature_topic: "tomerfi_thermostat/<thermostat_name>/current_temperature"
  mode_command_topic: "tomerfi_thermostat/<thermostat_name>/mode"
  modes:
    - "off"
    - "cool"
    - "heat"
  temperature_command_topic: "tomerfi_thermostat/<thermostat_name>/temperature"
  fan_mode_command_topic: "tomerfi_thermostat/<thermostat_name>/fan"
  fan_modes:
    - "auto"
    - "low"
    - "medium"
    - "high"
  min_temp: 17
  max_temp: 30
  temp_step: 1